import type {Metadata} from 'next'
import './globals.css'
import ReduxProvider from "@/app/redux/provider";
import dynamic from "next/dynamic";
import ReactQueryProvider from "@/app/utils/ReactQueryProvider";
import {ToastContainer} from "react-toastify";
import React from "react";
import RegisterModal from "@/app/components/modals/RegisterModal";
import ToastContainerApp from "@/app/utils/ToastContainer";


export const metadata: Metadata = {
    title: 'Trip Tour',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ReactQueryProvider>
            <html lang="fa">
            <body className='font-body'>
            <ReduxProvider>
                <ToastContainerApp/>
                {children}
                <RegisterModal/>
            </ReduxProvider>
            </body>
            </html>
        </ReactQueryProvider>
    )
}
