import type {Metadata} from 'next'
import './globals.css'
import Footer from "@/app/components/footer/footer";
import ReduxProvider from "@/app/redux/provider";
import dynamic from "next/dynamic";
import ReactQueryProvider from "@/app/utils/ReactQueryProvider";
import {ToastContainer} from "react-toastify";
import React from "react";

const RegisterModal = dynamic(() => import('@/app/components/modals/RegisterModal'), {ssr: false})


export const metadata: Metadata = {
    title: 'Trip Tour',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ReactQueryProvider>
            <html lang="fa">
            <body className='font-body'>
            <ReduxProvider>
                {children}
                <RegisterModal/>
            </ReduxProvider>
            {/*<Footer/>*/}
            </body>
            </html>
        </ReactQueryProvider>
    )
}
