import type { Metadata } from 'next'
import './globals.css'
import Footer from "@/app/components/footer/footer";


export const metadata: Metadata = {
  title: 'Trip Tour',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body className='font-body'>
      {children}
      {/*<Footer/>*/}
      </body>
    </html>
  )
}
